{ config, lib, pkgs, options, ... }: {
  config.environment.systemPackages = with pkgs; [
    baobab
    blender
    brave
    celluloid
    charles3
    chromium
    discord
    etcher
    evince
    filezilla
    firefox
    foliate
    gimp-with-plugins
    gparted
    gthumb
    handbrake
    inkscape
    libreoffice
    musescore
    obs-studio
    obsidian
    pitivi
    protonmail-bridge
    remmina
    rhythmbox
    screenkey
    spotify
    transmission-gtk
    vscode
    wireshark
    zeal
  ];
}
