bind_host: 0.0.0.0
bind_port: 80
users:
- name: cameron
  password: $2a$10$duNKf8RhdH4D12qb0/ux5ev2l3xSqaLh08DQohjmo7ncyJYKXc30i
auth_attempts: 5
block_auth_min: 15
dns:
  bootstrap_dns:
  - 1.1.1.1
  bind_hosts:
  - 0.0.0.0
  port: 53
  protection_enabled: true
  upstream_dns:
  - tls://dot.tiar.app
  - tls://dns.adguard-dns.com
  - tls://dns.futuredns.me
  - tls://dns.decloudus.com
  - tls://dot.la.ahadns.net
  - tls://dot.ny.ahadns.net
  - tls://dot.chi.ahadns.net
  - tls://p2.freedns.controld.com