{ config, pkgs, ... }: {
  imports = [
    ../../global/global.nix
    ../../modules/common/fonts/fonts.nix
    ../../modules/common/shell/shell.nix
    ../../modules/common/user-main/user-main.nix
    ../../modules/common/utils/utils.nix
    ../../modules/nixos/__nixos/__nixos.nix
    ../../modules/nixos/application-desktop/application-desktop.nix
    ../../modules/nixos/application-desktop-gtk/application-desktop-gtk.nix
    ../../modules/nixos/desktop-environment-xfce/desktop-environment-xfce.nix
    ../../modules/nixos/display-manager-lightdm/display-manager-lightdm.nix
    ../../modules/nixos/service-nomachine/service-nomachine.nix
    ../../modules/nixos/service-audio/service-audio.nix
    ../../modules/nixos/service-avahi/service-avahi.nix
    ../../modules/nixos/service-cron/service-cron.nix
    ../../modules/nixos/service-docker/service-docker.nix
    ../../modules/nixos/service-firewall/service-firewall.nix
    ../../modules/nixos/service-networking/service-networking.nix
    ../../modules/nixos/service-samba/service-samba.nix
    ../../modules/nixos/service-ssh/service-ssh.nix
    ../../modules/nixos/service-sudo/service-sudo.nix
    ../../modules/nixos/service-virtualbox/service-virtualbox.nix
    ./modules/cron.nix
    ./modules/filesystems.nix
    ./modules/development.nix
    ./modules/docker.nix
    ./modules/docker-resiliosync.nix
    ./modules/docker-swag.nix
    ./modules/networking.nix
    ./modules/samba.nix
    ./modules/users.nix
    ./modules/vscode-remote.nix
    ./modules/work.nix
  ];
}
